spring:
  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
        ##physical_naming_strategy: com.toongather.toongather.global.config.UpperCaseNamingStrategy
    hibernate:
      ddl-auto: none
  thymeleaf:
    prefix: classpath:/templates
    cache: false
    order: 0

  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/C:\project\simjeom    # 자신에 맞춰 바꾸기
    username: sa
    password: 123

logging.level:
  root: ERROR
  org.hibernate.SQL: debug
  org.hibernate.type.descriptor.sql: trace
  com.simjeom.simjeom.domain: debug

